import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

// A4 portrait in PDF points (72pt = 1in).
const A4 = { w: 595.28, h: 841.89 };
const GAP = 18;

/**
 * Compose one downloadable PDF that lays the courier's own slip/label pages
 * TWO-PER-A4-PAGE (top + bottom), preserving each slip's aspect ratio. `sources`
 * is an ordered list of courier label PDFs — for Trax that's one buffer per
 * parcel (single page each), for PostEx/Rocket a combined multi-page buffer;
 * either way every page of every source is flattened in order and paginated 2-up.
 * The courier's artwork is embedded as-is (vector, scannable barcode intact) —
 * we only scale + position it, never re-render it.
 */
export async function compose2Up(sources: Buffer[]): Promise<Buffer> {
  const out = await PDFDocument.create();
  const embedded = [];
  for (const buf of sources) {
    let src: PDFDocument;
    try {
      src = await PDFDocument.load(buf, { ignoreEncryption: true });
    } catch {
      continue; // skip an unreadable/HTML slip rather than fail the whole sheet
    }
    const pages = src.getPages();
    if (!pages.length) continue;
    const eps = await out.embedPages(pages);
    embedded.push(...eps);
  }
  if (!embedded.length) {
    throw new Error('No printable label pages could be read for these parcels.');
  }

  const slotH = (A4.h - GAP * 3) / 2; // two slots, gaps top/middle/bottom
  const slotW = A4.w - GAP * 2;
  for (let i = 0; i < embedded.length; i += 2) {
    const page = out.addPage([A4.w, A4.h]);
    const pair = embedded.slice(i, i + 2);
    pair.forEach((ep, k) => {
      const scale = Math.min(slotW / ep.width, slotH / ep.height, 1.6);
      const w = ep.width * scale;
      const h = ep.height * scale;
      const x = (A4.w - w) / 2;
      const slotBottomY = k === 0 ? A4.h - GAP - slotH : GAP;
      const y = slotBottomY + (slotH - h) / 2;
      page.drawPage(ep, { x, y, width: w, height: h });
    });
  }
  return Buffer.from(await out.save());
}

export interface PicklistRow {
  product: string;
  variant?: string | null;
  qty: number;
}

/**
 * A warehouse pick sheet: one row per product/variant with the TOTAL quantity to
 * pick across every parcel on a loadsheet. Generated by us (the couriers don't
 * provide it) — plain, printable, paginated.
 */
export async function buildPicklistPdf(opts: {
  title: string;
  subtitle?: string;
  rows: PicklistRow[];
  totalUnits: number;
  parcelCount: number;
}): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const M = 40;
  const ink = rgb(0.12, 0.12, 0.14);
  const grey = rgb(0.45, 0.45, 0.48);
  const line = rgb(0.85, 0.85, 0.88);

  // Column x-positions: Product | Variant | Qty (right-aligned).
  const colProduct = M;
  const colVariant = M + 250;
  const colQtyRight = A4.w - M;

  let page = doc.addPage([A4.w, A4.h]);
  let y = A4.h - M;

  const clip = (s: string, max: number, f = font, size = 10): string => {
    let t = s ?? '';
    while (t.length && f.widthOfTextAtSize(t, size) > max) t = t.slice(0, -1);
    return t.length < (s ?? '').length ? `${t.slice(0, -1)}…` : t;
  };

  // Header
  page.drawText(opts.title, { x: M, y: y - 4, size: 16, font: bold, color: ink });
  y -= 24;
  if (opts.subtitle) {
    page.drawText(clip(opts.subtitle, A4.w - M * 2, font, 10), {
      x: M,
      y,
      size: 10,
      font,
      color: grey,
    });
    y -= 16;
  }
  page.drawText(
    `${opts.parcelCount} parcels · ${opts.rows.length} SKUs · ${opts.totalUnits} units`,
    { x: M, y, size: 10, font, color: grey },
  );
  y -= 22;

  const drawHead = () => {
    page.drawText('Product', { x: colProduct, y, size: 9, font: bold, color: grey });
    page.drawText('Variant', { x: colVariant, y, size: 9, font: bold, color: grey });
    const qh = 'Qty';
    page.drawText(qh, {
      x: colQtyRight - bold.widthOfTextAtSize(qh, 9),
      y,
      size: 9,
      font: bold,
      color: grey,
    });
    y -= 6;
    page.drawLine({
      start: { x: M, y },
      end: { x: A4.w - M, y },
      thickness: 1,
      color: line,
    });
    y -= 14;
  };
  drawHead();

  for (const r of opts.rows) {
    if (y < M + 30) {
      page = doc.addPage([A4.w, A4.h]);
      y = A4.h - M;
      drawHead();
    }
    page.drawText(clip(r.product, colVariant - colProduct - 12), {
      x: colProduct,
      y,
      size: 10,
      font,
      color: ink,
    });
    page.drawText(clip(r.variant || '—', colQtyRight - colVariant - 40, font, 10), {
      x: colVariant,
      y,
      size: 10,
      font,
      color: r.variant ? ink : grey,
    });
    const qty = String(r.qty);
    page.drawText(qty, {
      x: colQtyRight - bold.widthOfTextAtSize(qty, 10),
      y,
      size: 10,
      font: bold,
      color: ink,
    });
    y -= 8;
    page.drawLine({
      start: { x: M, y },
      end: { x: A4.w - M, y },
      thickness: 0.5,
      color: line,
    });
    y -= 12;
  }

  return Buffer.from(await doc.save());
}
